name: flutter_photon_rs
description: Dart ffi to photon library, an image processing library written in rust. 
version: 0.0.1
homepage: https://github.com/bsteps/flutter_photon_rs
repository: https://github.com/bsteps/flutter_photon_rs
issue_tracker: https://github.com/bsteps/flutter_photon_rs/issues

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  ffigen: ^5.0.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.32.0
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.11
  freezed: ^2.0.3+1

flutter:
  plugin:
    platforms:
      android:
        package: com.bsteps.flutter_photon_rs
        pluginClass: FlutterPhotonRsPlugin
      ios:
        pluginClass: FlutterPhotonRsPlugin
